### ISSUE TITLE
develop open source software journal logo

### ISSUE THREAD

**Issue by vsoch** [tholman/generative-artistry#12]
hey @tholman ! Me again :) I'm working with @arfon @tylerburleigh @FelixHenninger and @jodeleeuw starting up a Journal for Research Software (or something along those lines, name not decided yet) and your beautiful artistry keeps coming back to me! To have a generative artistry-type logo that we can really easily modify, change up for different contexts, and generally have fun with, would be amazing! I'm not super experienced beyond using d3 and some other libraries, but do you have guidance or suggestion for some strategies we might take to go about this? I think we would want to come up with (another generative algorithm) to create a set of ideas, and then iterate on details from there. Thank you!

**Comment by tholman** [comment]
Heya, thanks for the kind words. If you're looking for some freelance work or advice you can shoot me an email :)

**Comment by vsoch** [comment]
Thanks a bunch :) I made a pretty terribly logo for now, but will keep you in mind for when we need a real / professional one, haha.
