### ISSUE TITLE
License for Finished Tutorial Code

### ISSUE THREAD

**Issue by jlarmstrongiv** [tholman/generative-artistry#19]
Hi, 

I found your [article](https://generativeartistry.com/tutorials/piet-mondrian/), “Generative Artistry: Piet Mondrian,” on [sidebar.io](https://sidebar.io) the other day.  I enjoyed the read, and thought the end result was really cool!

I’m just wondering—what is the license on the finished code?  It’d be cool if it were something like MIT so that others can play around, edit, experiment, and share their changes.  If not, that’s fine too.  Maybe there could be a spot to clarify what the license on either this [github repository](https://github.com/tholman/generative-artistry) or the footer of the creative artistry [website](https://generativeartistry.com/).

Keep up the great work! 🙂

**Comment by jlarmstrongiv** [comment]
Codepen licenses all public pens under MIT [automatically](https://blog.codepen.io/legal/licensing/).  While I suppose that could close this issue, it would still be nice to put that license more prominently in other places too 🎉

**Comment by tholman** [comment]
Added a license for the final code, for posterity (MIT)
