### ISSUE TITLE
Coffee link no work

### ISSUE THREAD

**Issue by remy** [tholman/generative-artistry#23]
https://github.com/tholman/generative-artistry/blob/db801f17f3d5ce512c2d4003b6a93c703ad154a8/layouts/partials/footer.html#L6

Sends off to 404. Figured you'd want to know, you know, to ensure the pending coffee avalanche that'll be delivered through the letter box (presumable frozen, otherwise you'd get all the coffee on the doormat - unless you sellotape a funnel to your letterbox and tube it directly to your coffee mug…but that seems complicated).

**Comment by tholman** [comment]
🙏🙏🙏 Removed for now, until we make a shared one for the project 🙏🙏🙏
