### ISSUE TITLE
Newest or Oldest Sketches First?

### ISSUE THREAD

**Issue by mattdesl** [tholman/generative-artistry#9]
First – this is a great resource, thanks for building it. 👏 🎉 

I'm pointing people to the website as it's a good beginner introduction to generative art (without npm/git/node/etc), but I'm wondering if it should be sorted in reverse order, so that newer tutorials appear at the bottom? This way it feels more like a guide: "Start with the basics, move your way up to more complex sketches." Or is it meant to feel more like a blog? "Here's the most recent tutorial."

I dunno.. just idle thoughts. 🤔

**Comment by tholman** [comment]
Yeah, I guess ultimately its meant to feel more like a blog. 

Ideally they won't get too much trickier code wise (although the last one had a little complex array manipulation) ... but then, I wonder if thats just wishful thinking as I eventually creep away from a lot of already explored ideas/replications of others art.

**Comment by tholman** [comment]
Wouldn't hurt to perhaps put together a learning guide or something, for those that are really interested. Something I'll take a look at 💃 ~ closing for now though
